// SPDX-License-Identifier: MPL-2.0
// Original contributions Copyright 2026 Nuri Bruner.

package run.nuri.getagrip.ui

import run.nuri.getagrip.R
import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

/// The four tabs, decided for good in Phase 8b; their icons redrawn 2026-09-30.
///
/// There is not much pure logic in a tab bar, which is exactly why this is worth pinning: the
/// icons and their ORDER are an identity decision that a stray import can change silently, and
/// nothing in a build failure would say so. The mapping from the SF Symbols the iOS app names
/// is recorded on `Tab`, next to the icons themselves.
class TabIconTests {

    /// **Order is the tab bar's contract**: Today first, then History, Maxes and Settings.
    @Test
    fun theFourTabsAreInTheirOrder() {
        assertEquals(listOf(Tab.Today, Tab.History, Tab.Maxes, Tab.Settings), Tab.entries)
        assertEquals(0, Tab.entries.indexOf(Tab.Today))
        assertEquals(1, Tab.entries.indexOf(Tab.History))
        assertEquals(2, Tab.entries.indexOf(Tab.Maxes))
        assertEquals(3, Tab.entries.indexOf(Tab.Settings))
    }

    /// The icons are the iOS custom symbols, generated into `res/drawable` by
    /// `scripts/make_symbols.swift --android` (docs/CUSTOM_SYMBOLS.md). Pinned by identity:
    /// a stray edit to the enum should fail here, not ship.
    @Test
    fun theTabsCarryTheGeneratedIcons() {
        assertEquals(R.drawable.ic_tab_today, Tab.Today.icon)
        assertEquals(R.drawable.ic_tab_history, Tab.History.icon)
        assertEquals(R.drawable.ic_tab_benchmarks, Tab.Maxes.icon)
        assertEquals(R.drawable.ic_tab_settings, Tab.Settings.icon)
    }

    /// **Outlined at rest, filled when selected** — Material's rule — except Today, which has
    /// ONE form on both platforms: a hollow finger is a loop, and a loop reads as a session.
    @Test
    fun selectionSwapsToTheFilledTwinExceptToday() {
        assertEquals(Tab.Today.icon, Tab.Today.selectedIcon)
        assertEquals(R.drawable.ic_tab_history_fill, Tab.History.selectedIcon)
        assertEquals(R.drawable.ic_tab_benchmarks_fill, Tab.Maxes.selectedIcon)
        assertEquals(R.drawable.ic_tab_settings_fill, Tab.Settings.selectedIcon)
        for (tab in listOf(Tab.History, Tab.Maxes, Tab.Settings)) {
            assertNotEquals(tab.icon, tab.selectedIcon, "${tab.name} should fill when selected")
        }
    }

    /// Four tabs, four different glyphs, in both states. A repeated icon reads as a broken
    /// build long before anyone reads the labels.
    @Test
    fun noTwoTabsShareAGlyph() {
        assertEquals(Tab.entries.size, Tab.entries.map { it.icon }.toSet().size)
        assertEquals(Tab.entries.size, Tab.entries.map { it.selectedIcon }.toSet().size)
    }

    /// **The drawables are generated, never hand-edited.** Each carries the generator's
    /// header; a file without it has been redrawn by hand and will be lost on the next run.
    /// None mirror in RTL: a calendar, a force peak, a gear and a hand on an edge all mean
    /// what they meant.
    @Test
    fun everyTabDrawableIsGeneratedAndUnmirrored() {
        val names = listOf("ic_tab_today", "ic_tab_history", "ic_tab_history_fill", "ic_tab_benchmarks",
            "ic_tab_benchmarks_fill", "ic_tab_settings", "ic_tab_settings_fill",
            "ic_glyph_gauge", "ic_glyph_export", "ic_glyph_log")
        for (name in names) {
            val xml = File("src/main/res/drawable/$name.xml").readText()
            assertTrue(xml.contains("GENERATED by scripts/make_symbols.swift"), "$name was edited by hand")
            assertTrue(!xml.contains("autoMirrored"), "$name should not mirror")
        }
    }

    /// **The label is resolved on READ, never baked in at construction.** Enum entries are
    /// built once when the class loads, so a translated string captured in the constructor
    /// would keep the language it was born in after the phone's language changed under a
    /// running process. Without a string lookup installed, `L10n.tr` echoes the key — which is
    /// the English, and is what this asserts.
    @Test
    fun everyTabResolvesItsLabelOnRead() {
        assertEquals("Today", Tab.Today.label)
        assertEquals("History", Tab.History.label)
        assertEquals("Benchmarks", Tab.Maxes.label)
        assertEquals("Settings", Tab.Settings.label)
    }
}
